apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cb500-monitor-data
  namespace: cb500f
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
